### ISSUE TITLE
How to indicate to analyse the testing branch?

### ISSUE THREAD

**Issue by yalh76** [YunoHost/CI_package_check#12]
package_check allows to specify the branch you want to check with the argument `--branch=` or `-b`
I haven't find a way to do the same with analyseCI.sh 

It would be useful for maintainers to let them schedule a batch of package_check on different packages before doing pull request between for example their testing and master branch

**Comment by maniackcrudelis** [comment]
Related to https://github.com/YunoHost/yunorunner/issues/3, I understand that you're building your own CI.
So, indeed CI_package_check doesn't manage branches. This feature should be implemented into those script. Which can be a little bit difficult due to the complexity of the CI.
Still, it could be done.

However, do you know our dev CI ? https://ci-apps-dev.yunohost.org/jenkins/
A [topic on our forum](https://forum.yunohost.org/t/proposition-for-a-new-non-official-ci/3595/6) explain how it works. It can maybe fulfills your expectations as packager.

(Sorry that for the moment this CI is down, the VPS itself has trouble...)

**Comment by yalh76** [comment]
Yes, as I saw a link to Yunorunner in your comments yesterday, I tried to install it to be able to launch batch of package_checker on testing or other package branches (I'm quite bored to wait package_check result on one of package to launch the next one)

If needed I already found an ugly workaround to check testing branches: in the pcheckCI.sh l183: directly adding -b testing

For the dev CI, I've seen it but without really looking what is was.... I will look when it will be up, thanks for the advise.

**Comment by maniackcrudelis** [comment]
> I'm quite bored to wait package_check result on one of package to launch the next one

We're discussing about that right now on the apps room ;)
I know it can be boring, especially for some very long apps to test.

On my side, I'm using 3 different virtual machine at the same time to not be bother by that problem.

> If needed I already found an ugly workaround to check testing branches: in the pcheckCI.sh l183: directly adding -b testing

The problem is more, how to pass the branch through the CI until this line.

**Comment by yalh76** [comment]
From my newbie point of view, not knowing pyhton, adding a third argument to the analyseCI.sh to let him save in the work list:
`$repo;$id;$test_name;$branch`
and then pcheckCI.sh can use the fourth argument in the work list to launch package_check with -b $branch argument

**Comment by maniackcrudelis** [comment]
Yep, that's would probably be easy to do for YunoRunner, but after that, you'll have to handle that fourth argument in analyseCI, pcheckCI and all other scripts that use those datas.
That's no big deal, but you'll have to be careful to not forgot any part. And there's many.

If you want to try to add that feature, I can help you.

**Comment by yalh76** [comment]
> On my side, I'm using 3 different virtual machine at the same time to not be bother by that problem.

I also have two and sometimes three VMs. But as far as I've understood CI_package check, we can have one yunorunner directly managing several package_check.

So my dream would be to add several package_check for different packages and different branches in the yunorunner and let the VMs do the job

**Comment by yalh76** [comment]
> 
> 
> Yep, that's would probably be easy to do for YunoRunner, but after that, you'll have to handle that fourth argument in analyseCI, pcheckCI and all other scripts that use those datas.
> That's no big deal, but you'll have to be careful to not forgot any part. And there's many.
> 
> If you want to try to add that feature, I can help you.

Thanks, I will first manage rainloop_ynh, make the CI_package_check I installed work, maybe take a look at the yunorunner_ynh_core package and then look at the branch argument ^^

**Comment by maniackcrudelis** [comment]
Currently YunoRunner is running only with one CI_package_check (but we have 4 YunoRunner on different servers)
CI_package_check can, on its side, manage several package_check, we used that feature for ARM tests, but only one at a time.

If you want indeed to run many tests on different packages and different branches. ci-apps-dev would be perfect, as it works directly on the directories you push into it, whatever the current branch.
Hope it will be back soon...
